### PR TITLE
Fix bug in editing quantity in `edito` to the same value

### LINKED ISSUE #180: [PE-D][Tester A] Same item is not collated together for an order for a single business owner
# Issue

The same item is not collated together for an order for a single business owner.

# Steps to Reproduce

First, we add an order with 20 `Table`.

1. Type and send `addo n/John Doe p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 `.
2. Type and send `i/ Table q/20`.
3. Type and send `done`.

The UI is as shown below:

4. Update the `Table` quantity to 20 (same as before, so there should ideally be no change in the user interface. **it is important to reproduce the bug by making sure the quantity is exactly the same as the quantity in the existing order**, for example editing the quantity here to 30 would not lead you to reproduce the bug): `edito 1 i/Table q/20` . However, the `Table` item is now duplicated.

5. Now, we try to update the `Table` quantity to 50, but only the first `Table` item is updated: `edito 1 i/Table q/50`

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: EmilyOng/ped#11

### PR DESCRIPTION
**Pull request by Jiacheng-y**
Add `else` block to handle the case of `edito` with same item quantity as currently in the order. 

Now, new items to be edited which are already in the order list will throw an error message to the user about the non-change in item quantity. 
#180

### CODE REVIEW

File: src/main/java/tracko/logic/commands/order/EditOrderCommand.java [hunk 1]
```diff
@@ -261,6 +264,10 @@ public void updateItemList(Order orderToEdit, ItemQuantityPair itemToEdit) throw
                     orderedItems.set(i, updatedItem);
                     hasItemBeenUpdated = true;
                     break;
+                } else {
+                    // else case where edited quantity = original quantity, throw new exception to warn of
+                    // no quantity change
+                    throw new CommandException(MESSAGE_NO_CHANGE_IN_QUANTITY);
```
Comment (melissaharijanto) [inline src/main/java/tracko/logic/commands/order/EditOrderCommand.java:275]: I think I mentioned something about this in the DG for `edito` implementation, I think I mentioned that nothing will happen if the quantity is the same; do you mind helping me change it?

**Review by melissaharijanto — APPROVED** [review]
Generally looks good!

File: src/main/java/tracko/logic/commands/order/EditOrderCommand.java (hunk 1 above)
Comment (Jiacheng-y) [reply src/main/java/tracko/logic/commands/order/EditOrderCommand.java:275]: Ah actually for this, should we allow the edit to go through if the quantity is the same? 
I was thinking about just setting
```java
hasItemBeenUpdated = true;
```
when quantity is the same. In this case the user will still see an item edited successfully confirmation message even when there are potentially no items actually edited.

Comment (melissaharijanto) [reply src/main/java/tracko/logic/commands/order/EditOrderCommand.java:275]: I think adding an exception is fine actually, so the user knows that the value is actually the same; otherwise the user won't know that the quantity has actually alr been updated and flag it as a bug (bc it doesnt change!)

**Review by janelleljt — APPROVED** [review]
Looks good!

File: src/main/java/tracko/logic/commands/order/EditOrderCommand.java (hunk 1 above)
Comment (Jiacheng-y) [reply src/main/java/tracko/logic/commands/order/EditOrderCommand.java:275]: ok, thank you :) 

I've updated the edito section in the DG to say this: 
```java
Otherwise, a `CommandException` with `MESSAGE_NO_CHANGE_IN_QUANTITY` will be thrown. 
This is to warn users that the newly inputted `Quantity` is the same as the existing `Quantity` 
and does not update the `Quantity` field at all. 
```
