### PR TITLE
Fix UI tags

### LINKED ISSUE #164: [PE-D][Tester E] Tag UI readability for items with extensive tags
When multiple tags are associated with an item, the wrap-around of characters in each tag reduces readability.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: zlimez/ped#3

### PR DESCRIPTION
**Pull request by melissaharijanto**
In this PR: 
- Tags are now limited to 30 characters. If the user inputs more than that, an error will be thrown
- `HBox` for tags is changed back to `FlowPane`.  Previously when suggesting the change, I was not aware that the `HBox` only lays its children in a single row, which is why it condensed everything to a vertical line when it does not fit. I also tried finding ways to set boundaries to the `FlowPane`, because apparently its behavior allows its children to overflow, however I could not find any way to do that. Limiting the tags' characters makes sure that the text will not overflow out of the box if it is too long.

Screen Shot 2022-11-01 at 00 44 33

Screen Shot 2022-11-01 at 00 45 08

### CODE REVIEW

**Review by janelleljt — APPROVED** [review]
Looks good!

File: src/main/java/tracko/model/tag/Tag.java [hunk 1]
```diff
@@ -9,7 +9,8 @@
  */
 public class Tag {
 
-    public static final String MESSAGE_CONSTRAINTS = "Tags names should be alphanumeric";
+    public static final String MESSAGE_CONSTRAINTS = "Tags names should be alphanumeric and "
+            + "should not be more than 30 characters long.";
```
Comment (donljh) [inline src/main/java/tracko/model/tag/Tag.java]: Little grammatical error here --> `Tags name` should be `A tag's name` or `Tags' names`. Think the former would be good!

**Review by donljh — CHANGES_REQUESTED** [review]

File: src/main/java/tracko/model/tag/Tag.java (hunk 1 above)
Comment (melissaharijanto) [reply src/main/java/tracko/model/tag/Tag.java]: Thanks for pointing it out!

**Review by donljh — APPROVED** [review]
